### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by ts4iot** [BCN3D/Stratos#22]
Do the BCN3D Epsilon printers support the Ultimaker/Cura API?

**Comment by marcmateo** [comment]
Hello @ts4iot ,

In order to better understand your question, for what purpose do you want to use the Ultimaker API ?

Regards,
Marc Mateo

**Comment by ts4iot** [comment]
Hi Mateo,

I cannot send you all the information on github. Is email m?????@bcn3d.com correct?

Best regards,
Markus

**Comment by marcmateo** [comment]
Hello @ts4iot ,

Send an email to the address support@bcn3d.com and we will try to answer it as soon as possible.

Regards,
Marc Mateo
