### ISSUE TITLE
Incorrect naming in the variant files for hotends for Sigma and Sigmax. Due to this the E3D hotends can not be used in Stratos.

### ISSUE THREAD

**Issue by Prejkox** [BCN3D/Stratos#6]
**Application version**
Stratos 1.0.0

**Platform**
Windows 10

**Printer**
Sigma and Sigmax

**Reproduction steps**
1. Added printer
2. Tried to change hotend to E3D hotend but it is not in the drop down menu.
3. I checked in the directory "C:\Program Files\BCN3D Stratos 1.0.0\resources\variants\bcn3dsigma" and "C:\Program Files\BCN3D Stratos 1.0.0\resources\variants\bcn3dsigmax" and the *E3D*.cfg files are there so they should show up.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/31192882/126050821-fbcd5f7e-d408-42e7-a661-160701cc30d5.png)
![image](https://user-images.githubusercontent.com/31192882/126050901-020bce8b-0bb6-476b-a6c0-19bb88d08aa1.png)

**Actual results**
E3D hotends do not show up for Sigma and Sigmax in Stratos under drop down menu "Hotend" 

**Expected results**
E3D hotends should show up for Sigma and Sigmax in Stratos under drop down menu "Hotend"

**Project file**
Not applicable

**Log file**
Not applicable

**Additional information**
Did some investigation and found the reason to the error. It is the naming on row 2 in the *e3d*.cfg file. It is missing the E3D infront of the size of the nozzle. Due to this I think it is a gamble what Stratos chooses for hotend for the Sigma and Sigmax in current version as both have the same name.
Solution is to add E3D before the nozzle size. 

![image](https://user-images.githubusercontent.com/31192882/126051152-180df27e-9c4c-4a0a-ae6c-45fbec66fdfa.png)

**Comment by marcmateo** [comment]
Hello @Prejkox,

In Stratos we have made a change in the names of the hotends to simplify them for users, for this reason in the selector you don't see the E3D, although internally it's the same hotend as always.

Please, if you detect any strange behavior or failure regarding this issue, let us know and we will try to resolve it as soon as possible.


Regards
Marc
