### ISSUE TITLE
BCN3D BVOH filament not compatible on sigmax?

### ISSUE THREAD

**Issue by LuisCRSousa** [BCN3D/Stratos#7]
BCN3D BVOH filament seems to not be compatible in this software profiles on sigmax.

The first version of this software should support all of the printers and filaments of the main company.

**Comment by marcmateo** [comment]
Hello @LuisCRSousa ,

We are currently working on the BVOH profiles for  Sigmax. If you need to use this material in the printers you mentioned, I recommend looking at the parameters of the  PVA profiles and set the printing temperature at 210 degrees.

For any other question, do not hesitate to contact us.

Regards,
Marc
