### ISSUE TITLE
Preheat issue, PVA cloggs, BVOH compatibility

### ISSUE THREAD

**Issue by Pyrgator** [BCN3D/Stratos#8]
When printing using both hotends, one for main material other for PVA/BVOH support the printer preheats both hotends to printing temperature instead of one to standby and other to printing. With big prints this causes PVA to clogg the nozzle.
Also during the print the printer never cools to standby temperature, just cools down a little, also causing PVA to clogg the nozzle.
BVOH isnt supported in Stratos. Both PVA and BVOH profiles need tuning, for example fan speed is too high for both filaments.

**Application version**
1.0

**Platform**
Win10

**Printer**
Sigmax R19

**Comment by LuisCRSousa** [comment]
I'm having exactly the same problem.
Seems impossible to print with BVOH or PVA. The support extrudder starts heating like magic when's in standby for longs periods of time and it gets clogged right away after.

**Comment by Pyrgator** [comment]
Are you guys going to reply?

**Comment by mpikmwm** [comment]
got the same problem, right extruder clogged, after printig with bvoh

**Comment by Pyrgator** [comment]
Hey, are you serious? Is this company real? Where is any answer?

**Comment by marcmateo** [comment]
Hello,

Thanks for the report, we are working to solve the problems you mentioned to be able to integrate it in the next release, for now, we recommend you to lower the "Standby Temperature" setting from 150ºC to 100ºC, with this change you should notice an important improvement. If the problem persists after changing this, please contact us and we will try to solve it as soon as possible.
 
Regards,
Marc

**Comment by Pyrgator** [comment]
Lowering the temperature doesnt work, I have already tried that. To integrate it into slicer-  you promised this when there was "old" BCN-Cura. The problem persists, this is how Im contacting you.

**Comment by marcmateo** [comment]
Hello @Pyrgator ,

We also recommend adjusting the Start Purge Speed setting up to 5mm/s on both heads. If you still cannot get the desired results or any other question, do not hesitate to contact us.

Regards,
Marc

**Comment by marcmateo** [comment]
Hello @Pyrgator ,

If you are still having printing problems, please send us the Stratos Project File so we can analyze it and find a better solution. In the following [link ](https://www.bcn3d.com/bcn3d-support/)you will find the form to contact us and send the project, as well as other information to help you better.

Regards,
Marc
